name: CI MLflow Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow dagshub scikit-learn pandas
          
      - name: Run MLflow Project
        run: mlflow run MLProject --env-manager=local
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/adiawaly/MLOps_Food_Delivery.mlflow
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        # Kita wajib memasukkan env credentials di sini juga agar Python bisa login ke DagsHub
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/adiawaly/MLOps_Food_Delivery.mlflow
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        run: |
          # 1. Ambil Run ID terbaru langsung dari DagsHub menggunakan Python API
          RUN_ID=$(python -c "import mlflow; print(mlflow.search_runs(experiment_names=['Food_Delivery_Classification'], order_by=['start_time DESC']).iloc[0]['run_id'])")
          
          echo "Berhasil mendapatkan Run ID dari DagsHub: $RUN_ID"
          
          # 2. Build Docker Image
          mlflow models build-docker --model-uri runs:/$RUN_ID/model --name ${{ secrets.DOCKERHUB_USERNAME }}/food-delivery-model:latest
          
          # 3. Push ke Docker Hub
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/food-delivery-model:latest